<?php

declare(strict_types=1);

// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
// To regenerate: cargo run -p kreuzberg-e2e-generator -- generate --lang php

// Tests for render fixtures.

namespace E2EPhp\Tests;

use E2EPhp\Helpers;
use Kreuzberg\Kreuzberg;
use PHPUnit\Framework\TestCase;

class RenderTest extends TestCase
{
    public function it_renders_render_custom_dpi(): void
    {
        $documentPath = Helpers::resolveDocument('pdf/tiny.pdf');
        if (!file_exists($documentPath)) {
            $this->markTestSkipped('Missing document: ' . $documentPath);
        }
        $pngData = Kreuzberg::render_pdf_page($documentPath, 0, 72);
        Helpers::assertIsPng($pngData);
        Helpers::assertMinByteLength($pngData, 50);
    }

    public function it_renders_render_iterator(): void
    {
        $documentPath = Helpers::resolveDocument('pdf/tiny.pdf');
        if (!file_exists($documentPath)) {
            $this->markTestSkipped('Missing document: ' . $documentPath);
        }
        $pages = [];
        foreach (Kreuzberg::render_pdf_pages_iter($documentPath, 150) as $pngData) {
            Helpers::assertIsPng($pngData);
            $pages[] = $pngData;
        }
        $this->assertGreaterThanOrEqual(1, count($pages),
            sprintf('Expected at least 1 pages, got %d', count($pages)));
    }

    public function it_renders_render_single_page(): void
    {
        $documentPath = Helpers::resolveDocument('pdf/tiny.pdf');
        if (!file_exists($documentPath)) {
            $this->markTestSkipped('Missing document: ' . $documentPath);
        }
        $pngData = Kreuzberg::render_pdf_page($documentPath, 0, 150);
        Helpers::assertIsPng($pngData);
        Helpers::assertMinByteLength($pngData, 100);
    }

}
