// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
// To regenerate: cargo run -p kreuzberg-e2e-generator -- generate --lang typescript

// Tests for render fixtures.

import { describe, it, expect } from "vitest";
import { existsSync } from "node:fs";
import { renderPdfPageSync, JsPdfPageIterator } from "@kreuzberg/node";
import { helpers } from "./helpers";

describe("render", () => {
    it("render_custom_dpi", () => {
        const documentPath = helpers.resolveDocument("pdf/tiny.pdf");
        if (!existsSync(documentPath)) return;
        const pngData = renderPdfPageSync(documentPath, 0, { dpi: 72 });
        helpers.assertIsPng(pngData);
        helpers.assertMinByteLength(pngData, 50);
    });

    it("render_iterator", () => {
        const documentPath = helpers.resolveDocument("pdf/tiny.pdf");
        if (!existsSync(documentPath)) return;
        const pages: Buffer[] = [];
        const iter = new JsPdfPageIterator(documentPath, { dpi: 150 });
        for (const pngData of iter) {
            helpers.assertIsPng(pngData);
            pages.push(pngData);
        }
        expect(pages.length).toBeGreaterThanOrEqual(1);
    });

    it("render_single_page", () => {
        const documentPath = helpers.resolveDocument("pdf/tiny.pdf");
        if (!existsSync(documentPath)) return;
        const pngData = renderPdfPageSync(documentPath, 0, { dpi: 150 });
        helpers.assertIsPng(pngData);
        helpers.assertMinByteLength(pngData, 100);
    });

});
