package com.kreuzberg.e2e;

// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
// To regenerate: cargo run -p kreuzberg-e2e-generator -- generate --lang java

import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.PdfPageIterator;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

/** Tests for render fixtures. */
public class RenderTest {

    @Test
    public void renderCustomDpi() throws Exception {
        Path documentPath = E2EHelpers.resolveDocument("pdf/tiny.pdf");
        assumeTrue(Files.exists(documentPath),
                "Skipping render_custom_dpi: missing document");
        byte[] pngData = Kreuzberg.renderPdfPage(documentPath.toString(), 0, 72);
        E2EHelpers.assertIsPng(pngData);
        E2EHelpers.assertMinByteLength(pngData, 50);
    }

    @Test
    public void renderIterator() throws Exception {
        Path documentPath = E2EHelpers.resolveDocument("pdf/tiny.pdf");
        assumeTrue(Files.exists(documentPath),
                "Skipping render_iterator: missing document");
        int pageCount = 0;
        try (PdfPageIterator iter = new PdfPageIterator(documentPath.toString(), 150)) {
            while (iter.hasNext()) {
                byte[] pngData = iter.next();
                E2EHelpers.assertIsPng(pngData);
                pageCount++;
            }
        }
        assertTrue(pageCount >= 1,
                String.format("Expected at least 1 pages, got %d", pageCount));
    }

    @Test
    public void renderSinglePage() throws Exception {
        Path documentPath = E2EHelpers.resolveDocument("pdf/tiny.pdf");
        assumeTrue(Files.exists(documentPath),
                "Skipping render_single_page: missing document");
        byte[] pngData = Kreuzberg.renderPdfPage(documentPath.toString(), 0, 150);
        E2EHelpers.assertIsPng(pngData);
        E2EHelpers.assertMinByteLength(pngData, 100);
    }

}
