// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
// Category: render

package e2e

import (
	"os"
	"testing"

	"github.com/kreuzberg-dev/kreuzberg/packages/go/v4"
)

func TestRenderRenderCustomDpi(t *testing.T) {
	documentPath := ensureDocument(t, "pdf/tiny.pdf", true)
	if _, err := os.Stat(documentPath); os.IsNotExist(err) {
		t.Skipf("Skipping render_custom_dpi: missing document", "pdf/tiny.pdf")
	}
	pngData, err := kreuzberg.RenderPdfPage(documentPath, 0, kreuzberg.WithDPI(72))
	if err != nil {
		t.Fatalf("RenderPdfPage failed: %v", err)
	}
	assertIsPng(t, pngData)
	assertMinByteLength(t, pngData, 50)
}

func TestRenderRenderIterator(t *testing.T) {
	documentPath := ensureDocument(t, "pdf/tiny.pdf", true)
	if _, err := os.Stat(documentPath); os.IsNotExist(err) {
		t.Skipf("Skipping render_iterator: missing document", "pdf/tiny.pdf")
	}
	iter, err := kreuzberg.NewPdfPageIterator(documentPath, kreuzberg.WithDPI(150))
	if err != nil {
		t.Fatalf("NewPdfPageIterator failed: %v", err)
	}
	defer iter.Close()
	pageCount := 0
	for iter.Next() {
		pngData := iter.Page()
		assertIsPng(t, pngData)
		pageCount++
	}
	if err := iter.Err(); err != nil {
		t.Fatalf("iterator error: %v", err)
	}
	if pageCount < 1 {
		t.Fatalf("expected at least 1 pages, got %d", pageCount)
	}
}

func TestRenderRenderSinglePage(t *testing.T) {
	documentPath := ensureDocument(t, "pdf/tiny.pdf", true)
	if _, err := os.Stat(documentPath); os.IsNotExist(err) {
		t.Skipf("Skipping render_single_page: missing document", "pdf/tiny.pdf")
	}
	pngData, err := kreuzberg.RenderPdfPage(documentPath, 0, kreuzberg.WithDPI(150))
	if err != nil {
		t.Fatalf("RenderPdfPage failed: %v", err)
	}
	assertIsPng(t, pngData)
	assertMinByteLength(t, pngData, 100)
}
